# Generated by Django 5.2.4 on 2025-08-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the document', max_length=255)),
                ('file', models.FileField(help_text='Document file (images, PDFs, etc.)', upload_to='documents/')),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR code image for this document', null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the document was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the document was last updated')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
