# Generated by Django 5.2.4 on 2025-08-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='html_content',
            field=models.TextField(blank=True, help_text='HTML content generated from OCR processing', null=True),
        ),
    ]
