# Generated by Django 5.2.4 on 2025-08-13 11:09

import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_document_html_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='html_content',
        ),
        migrations.AddField(
            model_name='document',
            name='current_version_no',
            field=models.IntegerField(default=1, help_text='Current version number'),
        ),
        migrations.AddField(
            model_name='document',
            name='html',
            field=models.TextField(blank=True, help_text='HTML source of truth for the document', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='search_tsv',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Full-text search vector', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, help_text='Plain text generated from HTML for search indexing', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Generated QR code image for this document (legacy)', null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'user'), ('group', 'group'), ('share_link', 'share_link')], max_length=16)),
                ('subject_id', models.UUIDField()),
                ('role', models.CharField(choices=[('OWNER', 'OWNER'), ('EDITOR', 'EDITOR'), ('VIEWER', 'VIEWER')], max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_acls', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='my_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField(blank=True, null=True)),
                ('media_type', models.TextField()),
                ('filename', models.TextField()),
                ('data', models.BinaryField()),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='my_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='my_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RELATED', 'RELATED'), ('REVISION_OF', 'REVISION_OF'), ('REFERENCES', 'REFERENCES')], max_length=32)),
                ('from_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='my_app.document')),
                ('to_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='my_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='QRLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField(blank=True, null=True)),
                ('code', models.TextField(unique=True)),
                ('sig', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_qr_links', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_links', to='my_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'OWNER'), ('EDITOR', 'EDITOR'), ('VIEWER', 'VIEWER')], max_length=16)),
                ('token', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='my_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW', 'VIEW'), ('EDIT', 'EDIT'), ('SHARE', 'SHARE'), ('EXPORT', 'EXPORT')], max_length=16)),
                ('version_no', models.IntegerField(blank=True, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.document')),
                ('qr_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.qrlink')),
                ('share_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.sharelink')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.collection')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.document')),
            ],
            options={
                'unique_together': {('document', 'collection')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField()),
                ('html', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('search_tsv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('change_note', models.TextField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='authored_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='my_app.document')),
            ],
            options={
                'unique_together': {('document', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='DocumentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.label')),
            ],
            options={
                'unique_together': {('document', 'label')},
            },
        ),
    ]
