# Generated by Django 5.2.4 on 2026-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_remove_custom_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='document',
            name='qr_code_data',
            field=models.BinaryField(blank=True, help_text='QR code PNG image stored as binary in the database', null=True),
        ),
    ]
