# Generated by Django 5.2.4 on 2026-02-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_add_group_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
